### ISSUE TITLE
Couldn't compile with CoreRT

### ISSUE THREAD

**Issue by erdembayar** [MichalStrehovsky/SeeSharpSnake#25]
Getting following error. Am I missing something?

```
dotnet publish -r win-x64 -c Release /p:Mode=CoreRT
MSBuild version 17.4.0+18d5aef85 for .NET
  Determining projects to restore...
  Restored C:\test\SeeSharpSnake.csproj (in 287 ms).
  SeeSharpSnake -> C:\test\SeeSharpSnake\bin\Release\netcoreapp3.1\win-x64\SeeSharpSnake.dll
  Generating compatible native code. To optimize for size or speed, visit https://aka.ms/OptimizeCoreRT
C:\Program Files\dotnet\sdk\7.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ConflictResolution.targets(112,5): err
or NETSDK1152: Found multiple publish output files with the same relative path: C:\test\SeeSharpS
nake\obj\Release\netcoreapp3.1\win-x64\apphost.exe, bin\Release\netcoreapp3.1\win-x64\native\SeeSharpSnake.exe. [C:\test\SeeSharpSnake\SeeSharpSnake.csproj]
```

**Comment by MichalStrehovsky** [comment]
If you want .NET 7m there's a pull request with work in progress on that in #24.

It will probably need fixes like https://github.com/MichalStrehovsky/zerosharp/pull/37/commits/8ff3b934a440d7ea11fce2b3129ae3cb0a7894ba to finish that up.

It's not a huge priority for me because this kinds of things are a lot better to do with bflat: https://github.com/bflattened/bflat/tree/master/samples/Snake

**Comment by erdembayar** [comment]
Thank you.
I just created [global.json](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json) file to target sdk 3.1 instead, it compiles now, thank you for fun project.

```
{
    "sdk": {
      "version": "3.1.426",
      "rollForward": "latestFeature"
    }
  }
```
