### ISSUE TITLE
cant run on windows server 2008 r2 x64

### ISSUE THREAD

**Issue by sgf** [MichalStrehovsky/SeeSharpSnake#4]
cant run on windows server 2008 r2 x64

**Comment by MichalStrehovsky** [comment]
Is there a stack trace/error message?

**Comment by sgf** [comment]
nothing,just give me a error box. 
The application was unable to start correctly (0xc0000013), click ok to close the application.
![TIM图片20200117100914](https://user-images.githubusercontent.com/2557696/72578624-83ff5f00-3911-11ea-809a-2e75d75e9661.png)

![TIM图片20200117101045](https://user-images.githubusercontent.com/2557696/72578699-c4f77380-3911-11ea-8dbe-67e877fcfc97.png)

**Comment by sgf** [comment]
maybe because can't find api-ms-win-crt-string-l1-1-0.dll

![TIM图片20200117101724](https://user-images.githubusercontent.com/2557696/72578940-9332dc80-3912-11ea-864d-dd2fd7249cd5.png)

**Comment by sgf** [comment]
but im copy a dll from win10,even doesn't work.
![TIM图片20200117101959](https://user-images.githubusercontent.com/2557696/72579075-f3298300-3912-11ea-9edd-9289625ad23c.png)

cant find the entryPoint

**Comment by MichalStrehovsky** [comment]
Windows 10 comes with this preinstalled, but on old systems you need to get ucrt from Windows Update: get the DLL from the official place: https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows

The other option is to link against msvcrt.dll, but import libraries for that were last distributed around Visual C++ 6.0. Try searching for msvcrt.lib on the internet and pass that to link.exe instead of ucrt.lib. msvcrt.dll has been inbox with Windows since forever.

**Comment by sgf** [comment]
ok,thank you
